#!/usr/bin/env bash
cat <<'X'
00:02.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600]
00:14.3 Network controller: Intel Corporation Wi-Fi 6 AX201
00:1f.3 Audio device: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller
X
