#!/usr/bin/env bash
printf "makepkg %s\n" "$*" >>"${MOCK_LOG:?}"
printf "makepkg-source %s\n" "$(bash -c 'source ./PKGBUILD; printf "%s" "${source[0]}"')" >>"$MOCK_LOG"
# pretend we built something
[[ -n ${PKGDEST:-} && -z ${MOCK_MAKEPKG_FAIL:-} ]] && touch "$PKGDEST/cmaal-0.3.0.r1.gabc1234-1-any.pkg.tar.zst"
[[ -z ${MOCK_MAKEPKG_FAIL:-} ]]
